name 'serverdensity-serverdensity_agent'
version '0.9.4'
author 'Server Density'
summary 'Puppet module to install the Server Density monitoring agent and register servers automatically.'
description 'Official Puppet module for automatically installing the Server Density monitoring agent. Will install the agent packages, register new servers with the API and generate the correct config.'
license 'Simplified BSD License'
project_page 'https://github.com/serverdensity/puppet-serverdensity/'
dependency 'puppetlabs/apt', '>= 1.1.0'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
source 'https://github.com/serverdensity/puppet-serverdensity/'
